### ISSUE TITLE
Syncing seems to not work at all for me

### ISSUE THREAD

**Issue by jacobmischka** [shafreeck/slides#1]
This is a really cool project! The atom plugin is as well, really nice work.

I'm using chrome 53 and the slides don't seem to stay in sync. When browsing via the shareable link, the correct presentation doesn't open either. The filename and syncid are both correct. 

I receive two errors which I assume are the problem:

![image](https://cloud.githubusercontent.com/assets/3939997/16293082/934f5bce-38dc-11e6-9a0b-a5f84c5625bc.png)

I'm currently just using your demo site at http://shafreeck.github.io/slides/, it's possible this isn't a problem in master, though if not you should then probably update your demo site.

**Comment by shafreeck** [comment]
Yes, It was a problem of the demo site and now it is fixed. Now you can git it a try. Thanks very much for your feedback!
